alpha: 1
batch_size: 128
beta: 0
input_length: 256
learning_rate: 0.0001
lr_factor: 0.5
lr_patience: 10
mmd_type: rbf
num_classes: 2
reuse_target: false
source: CAL2-NI-20K
target: CAL2-NI-1K
test_size: 0.2
weight_decay: 0.0001
