alpha: 1.0
batch_size: 128
beta: 0.0
input_length: 256
learning_rate: 0.0001
lr_factor: 0.5
lr_patience: 10
mmd_type: rbf
num_classes: 3
reuse_target: false
source: CWRUA3
target: CWRUB3
test_size: 0.2
weight_decay: 0.0001
